### ISSUE TITLE
Errores al compilar

### ISSUE THREAD

**Issue by roggarmar** [pumitahou/DuinoCoinEthernetMiner#3]
C:\Users\R. García\Desktop\Ethernet\DuinoCoinEthernetMiner-main\arduinoETH\arduinoETH.ino:48:1: error: 'Sha1Wrapper' does not name a type
C:\Users\R. García\Desktop\Ethernet\DuinoCoinEthernetMiner-main\arduinoETH\arduinoETH.ino: In function 'uintDiff ducos1a(String, String, uintDiff)':
C:\Users\R. García\Desktop\Ethernet\DuinoCoinEthernetMiner-main\arduinoETH\arduinoETH.ino:199:3: error: 'Sha1_base' was not declared in this scope
C:\Users\R. García\Desktop\Ethernet\DuinoCoinEthernetMiner-main\arduinoETH\arduinoETH.ino:204:5: error: 'Sha1' was not declared in this scope
C:\Users\R. García\Desktop\Ethernet\DuinoCoinEthernetMiner-main\arduinoETH\arduinoETH.ino:204:5: note: suggested alternative: 'SPR1'
Compilation error: exit status 1}

**Comment by roggarmar** [comment]
Errores encontrados al compilar el archivo arduinoETH.ino

**Comment by pumitahou** [comment]
yes the error is this, the name of file not is the same name to main folder, and arduino ide make folder to file, you need put same name to folder in .ino file

now is fixed

**Comment by roggarmar** [comment]
Thank you very much for your very fast response. This afternoon I will apply your instructions. I regret that I followed an unorthodox path to expose my doubt. Excuse my inexperience.
Roger

**Comment by pumitahou** [comment]
No thanks, to report this error
